name: CatPipeline

on: [push]

env:
  AWS_REGION : "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::044798518090:role/GHtoAWSRole
          role-session-name: githubActions
          mask-aws-account-id: false
          role-skip-session-tagging: true

      - name: Start CodeBuild project
        run: aws codebuild start-build --project-name catpipeline-build
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

