name: CatPipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-role-to-assume: arn:aws:iam::044798518090:role/GithubOIDCRole
          role-session-name: github
          aws-region: us-east-1
          aws-role-duration-seconds: 3600

      - name: Start CodeBuild project
        run: aws codebuild start-build --project-name catpipeline-build
        env:
          AWS_DEFAULT_REGION: us-east-1

